export type widgetDetails = {
    id: number;
    campaign_id: number;
    widget_type: string;
    color: string;
    header_title: string;
    description: string;
    button_text: string;
    banner_image_url: string;
    field_label_1: string;
    field_label_2: string;
    button_color: string;
    widget_height: string;
    widget_width: string;
    body_text: string;
    background_image: string;
    join_button_text: string;
    template_id: number;
    popup_button_text: string;
    popup_button_color: string;
    popup_button_position: string;
    text_color: string;
    placement: string;
    background_type: string;
    background_color: string;
    success_message: string;
    stats_on: '1',
    stats_start_participants: number;
    stats_start_shares: number;
    stats_start_clicks: number;
    stats_start_impressions: number;
    header_font_color: string;
    left_image: string;
    allow_countdown: number;
    countdown_end: string;
    header_background_type: string;
    header_description_color: string;
}