import type { Metadata } from "next";
import "../globals.scss";
import Header from "@/app/(layout)/(admin)/Header";
import SidebarMenu from "../(layout)/(admin)/_components/SidebarMenu";

export const metadata: Metadata = {
  title: "Referral Framework",
  description: "Generated by create next app"
};

import { Getwlsettings } from "@/data/data";

const AdminLayout = async ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const c = await Getwlsettings();
  return (
    <>
      <html lang="en">
        <body className="bg-white">
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <SidebarMenu logo={c.data.logo} />
            <div className="flex flex-col">
              <Header logo={c.data.logo} />
              {children}
            </div>
          </div>
        </body>
      </html>
    </>
  );
};
export default AdminLayout;
