import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "../globals.scss";
import Header from "@/app/(layout)/(admin)/Header";
import Footer from "@/app/(layout)/(admin)/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Referral Framework",
  description: "Generated by create next app"
};

export default function AdminLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <>{children}</>
      <Footer />
    </>
  );
}
